# Generated by Django 5.2 on 2025-04-16 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=255)),
                ('ano_fundacao', models.IntegerField(default=2020)),
                ('pontos', models.IntegerField(default=70)),
            ],
        ),
        migrations.CreateModel(
            name='Batalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(blank=True, max_length=255, null=True)),
                ('startup_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batalha_startup_1', to='torneio.startup')),
                ('startup_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batalha_startup_2', to='torneio.startup')),
                ('vencedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batalhas_vencidas', to='torneio.startup')),
            ],
        ),
    ]
