# Generated by Django 5.2 on 2025-04-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='bugs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='investidores_irritados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='penalidades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='pitchs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='tracoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='startup',
            name='ano_fundacao',
            field=models.IntegerField(),
        ),
    ]
