# Generated by Django 5.2 on 2025-04-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0002_startup_bugs_startup_investidores_irritados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batalha',
            name='evento',
        ),
        migrations.AddField(
            model_name='batalha',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
