# Generated by Django 5.2 on 2025-04-17 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0003_remove_batalha_evento_batalha_concluida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='tracoes',
            new_name='tracao',
        ),
    ]
