# Generated by Django 5.2 on 2025-04-17 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0004_rename_tracoes_startup_tracao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='tracao',
            new_name='tracoes',
        ),
    ]
