# Generated by Django 5.2 on 2025-04-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0005_rename_tracao_startup_tracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='fake_news',
            field=models.IntegerField(default=0),
        ),
    ]
