# Generated by Django 5.2 on 2025-04-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0006_startup_fake_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batalha',
            name='id',
        ),
        migrations.AddField(
            model_name='batalha',
            name='batalha_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
