# Generated by Django 5.2 on 2025-04-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0007_remove_batalha_id_batalha_batalha_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batalha',
            name='batalha_id',
        ),
        migrations.AddField(
            model_name='batalha',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
