# Generated by Django 5.2 on 2025-04-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0008_remove_batalha_batalha_id_batalha_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='batalha',
            name='evento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
