# Generated by Django 5.2 on 2025-04-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0009_batalha_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_andamento', models.BooleanField(default=False)),
                ('finalizado', models.BooleanField(default=False)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
