# Generated by Django 5.2 on 2025-04-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0010_torneio'),
    ]

    operations = [
        migrations.AddField(
            model_name='batalha',
            name='eventos_startup_1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batalha',
            name='eventos_startup_2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batalha',
            name='shark_fight',
            field=models.BooleanField(default=False),
        ),
    ]
