# Generated by Django 5.2 on 2025-04-23 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0011_batalha_eventos_startup_1_batalha_eventos_startup_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batalha',
            name='vencedor',
        ),
        migrations.AddField(
            model_name='batalha',
            name='fase',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='batalha',
            name='vencedora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitorias', to='torneio.startup'),
        ),
    ]
