# Generated by Django 5.2 on 2025-04-23 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0012_remove_batalha_vencedor_batalha_fase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batalha',
            name='vencedora',
        ),
        migrations.AddField(
            model_name='batalha',
            name='vencedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batalhas_vencidas', to='torneio.startup'),
        ),
    ]
